image: "ruby:2.2.0"

services:
  - postgres:latest

variables:
  POSTGRES_DB: touchcard_test

# Cache gems in between builds
cache:
  paths:
    - vendor/ruby

before_script:
  - apt-get update -qq && apt-get install -y -qq postgresql postgresql-contrib libpq-dev cmake
  - ruby -v
  # Uncomment next line if your rails app needs a JS runtime:
  # - apt-get update -q && apt-get install nodejs -yqq
  - gem install bundler  --no-ri --no-rdoc
  - RAILS_ENV=test bundle install -j $(nproc) --path vendor
  - RAILS_ENV=test bundle exec rake db:create db:schema:load
  
rspec:
  script:
  - RAILS_ENV=test bundle exec rspec
